image: androidsdk/android-30

clone:
  depth: full              # SonarCloud scanner needs the full history to assign issues properly

definitions:
  caches:
    sonar: ~/.sonar/cache  # Caching SonarCloud artifacts will speed up your build

  steps:
    - step: &build-test-sonarcloud
        name: Build, test and analyze on SonarCloud
        caches:
          - gradle
          - sonar
        script:
          - pipe: sonarsource/sonarcloud-scan:1.3.0
            variables:
              SONAR_SCANNER_OPTS: -Xmx512m
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.5
        artifacts:
          - build/libs/**
    - step: &android-lint
        name: Android lint pass check
        caches:
          - gradle
        script:
          - ./gradlew lintRelease
        artifacts:
          - app/build/reports/**

pipelines:                 # More info here: https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html
  branches:
    master:
      - step: *build-test-sonarcloud
      - step: *android-lint
    develop:
      - step: *build-test-sonarcloud
      - step: *android-lint

  pull-requests:
    '**':
      - step: *build-test-sonarcloud
      - step: *android-lint
